resources:
- name: git-assets
  type: git
  source:
    branch: master
    uri: https://github.com/arulvannala/concourse-workshop

jobs:
- name: hello
  plan:
  - get: git-assets   # Lines to add
    trigger: true     # Lines to add
  - task: howdy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, My first pipeline!"]
